### ISSUE TITLE
1.4 词法解析器

### ISSUE THREAD

**Issue by QiGangs** [hsiaosiyuan0/icj#1]
第一次测试 Lexer 效果时，code 赋值为 'hi "lexer"'
输出的token 应为 hi 和 lexer
文章里写的是 hi 和 string

**Comment by QiGangs** [comment]
有最后一段代码中的 getPos() 方法，应该是类 Lexer 里面的。应该给个说明，我一开始还以为要把Source中的方法重写..

**Comment by hsiaosiyuan0** [comment]
谢谢

> 第一次测试 Lexer 效果时，code 赋值为 'hi "lexer"'
输出的token 应为 hi 和 lexer
文章里写的是 hi 和 string

篇幅里面的 `HI` 和 `STRING` 如果看了前文的话，应该可以知道说的是 token type。 为了描述更清楚一点，我增补为 `两个 Tokens，它们的类型分别是 HI 和 STRING`

> 有最后一段代码中的 getPos() 方法，应该是类 Lexer 里面的。应该给个说明，我一开始还以为要把Source中的方法重写..

因为是写到后面想起来最好在前面的章节里面做补充、这样读起来才会连贯一些，所以应该是增加时大意了
