### ISSUE TITLE
这么好的作品，不要断更啊

### ISSUE THREAD

**Issue by suhanyujie** [hsiaosiyuan0/icj#2]
哈喽 亲爱的 hsiaosiyuan0，首先感谢你写出这么好的文章。
拜读了你这本书，感觉对学习词法分析 语法解析有很大的帮助，无论是从行文，还是排版都是上上之作！请继续写下去，加油 ：）

**Comment by hsiaosiyuan0** [comment]
首先要谢谢你，也非常高兴可以帮到你。

现在进入全职工作的状态，所以时间上会不如之前多。

写着写着没有太好的反响、开始的热情也逐渐降低了，不过有时间的话还是会继续更新的。

其实编译器前端的内容已经差不多讲完了，没错就是这么简单，因为 Top-down 的解析器完全够用了。后端的话，没有静态类型的 JS 可以讲的内容其实也有限，多是运行时的优化，可能会离题比较远了；可以讲下如何生成代码，当下如果借助 babel 的话，其实只要简单变换下 AST、者最开始的时候就尽量地将节点结构设计得类似 [@babel/types](https://babeljs.io/docs/en/babel-types) 也就可以了。
